server:
   port: 8081
spring:
   dubbo:
      application: 
         name: dubbo-provider
         id: dubbo-provider
      registry: 
         protocol: zookeeper
         address: localhost:2181
      protocol:
         name: dubbo
         port: 2${server.port}
      server:
         true
      monitor:
         protocol: registry
