server:
   port: 80
   context-path: /

spring:
   datasource :
       url : jdbc:mysql://localhost:3306/test
       username : root
       password : qianhao123
       driver-class-name : com.mysql.jdbc.Driver
       
mybatis:
  mapper-locations:
    - classpath:com/**/mybatisxml/*.xml