server:
   port: 80
   context-path: /

spring:
   datasource :
       url : jdbc:mysql://localhost:3306/test
       username : root
       password : qianhao123
       driver-class-name : com.mysql.jdbc.Driver
   mail:
       host: smtp.163.com
       username: xiaoqianittest@163.com
       password: ---
       enable:  true
       smtp:
         auth: true
         starttls:
          enable: true
          required: true