server:
   port: 8082
spring:
   dubbo:
      application: 
         name: dubbo-consumer
         id: dubbo-consumer
      registry: 
         protocol: zookeeper
         address: localhost:2181
      protocol:
         name: dubbo
         port: 2${server.port}
      server:
         true
      monitor:
         protocol: registry