FROM openjdk:8u212-jre
LABEL author=Jason email=qianhao_cs@163.com

COPY target/SpringbootDemo-1.0-SNAPSHOT.jar /SpringbootDemo-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/SpringbootDemo-1.0-SNAPSHOT.jar"]